spring.application.name=demo
server.port=8080
# Giới hạn dung lượng tối đa cho mỗi file tải lên
spring.servlet.multipart.max-file-size=10MB

# Giới hạn tổng dung lượng cho một request (bao gồm cả file và các field khác)
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:mysql://localhost:3306/BT5?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
